name: Build Android APK

on:
  push:
    branches:
      - main  # Se ejecuta cuando haya un push en la rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Define variables de entorno necesarias para firmar tu APK
      KEYSTORE_PASSWORD: 123456
      KEY_PASSWORD: 123456
      STORE_FILE: ./android/my-upload-key.keystore
      MYAPP_UPLOAD_STORE_FILE: ./android/my-upload-key.keystore
      MYAPP_UPLOAD_KEY_ALIAS: my-key-alias
      MYAPP_UPLOAD_STORE_PASSWORD: 123456
      MYAPP_UPLOAD_KEY_PASSWORD: 123456

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' 

      - name: Install dependencies
        run: npm install  

      - name: Install JDK (Java Development Kit)
        uses: actions/setup-java@v1
        with:
          java-version: '11'  

      - name: Build the APK
        run: |
          cd android
          chmod +x gradlew 
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
